version: '3.7'
services:
 app:
  env_file:
    - .env
  restart: always
  container_name: app
  volumes:
   - ./:/app
   - ./sock:/sock
  build:
   context: .
   dockerfile: docker/docker_files/docker_app.conf
  command: sh -c "service supervisor start && uwsgi --ini /etc/uwsgi.ini"
  depends_on:
   - mongodb
   - rabbit
 nginx:
  env_file:
   - .env
  restart: always
  container_name: nginx
  volumes:
   - ./:/app
   - ./sock:/sock
  build:
   context: .
   dockerfile: docker/docker_files/docker_nginx.conf
  depends_on:
   - app
  ports:
    - "${APP_PORT}:8080"
 mongodb:
  env_file:
   - .env
  image: mongo:latest
  container_name: "mongodb"
  ports:
      - "${DB_PORT}:27017"
  command: mongod
 rabbit:
  env_file:
   - .env
  image: rabbitmq
  container_name: "${BROKER_HOST}"
  environment:
     - RABBITMQ_DEFAULT_USER=${BROKER_USERNAME}
     - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
  ports:
     - "${BROKER_PORT}:5672"
volumes:
 sock: